
def evently_params
  {:withdrawn=>"0",
   :olson_path=>"Europe/Rome",
   :children=>nil,
   :comments=>nil,
   :region_abbr=>"RM",
   :postal_code=>nil,
   :latitude=>"41.9",
   :all_day=>"0",
   :groups=>nil,
   :url=>"http://rome.eventful.com/events/workshop-wearable-technology-roma-/E0-001-092704646-3?utm_source=apis&utm_medium=apim&utm_campaign=apic",
   :id=>"E0-001-092704646-3",
   :address=>"Via Casilina 3T",
   :privacy=>"1",
   :links=>
    {:link=>
      [{:time=>"2016-04-15 06:32:12",
        :url=>"http://www.eventbrite.it/e/biglietti-workshop-wearable-technology-roma-24664172203?aff=ebapi",
        :id=>"277760683",
        :type=>"Info",
        :description=>"Event details at eventbrite.com!",
        :username=>"evdb"}]},
   :images=>
    {:image=>
      {:small=>{:width=>"48", :url=>"http://s4.evcdn.com/images/small/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png", "height"=>"48"},
       :width=>"48",
       :creator=>nil,
       :thumb=>{:width=>"48", :url=>"http://s4.evcdn.com/images/thumb/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png", "height"=>"48"},
       :height=>"48",
       :url=>"http://s4.evcdn.com/images/small/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png",
       :medium=>{:width=>"128", :url=>"http://s4.evcdn.com/images/medium/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png", "height"=>"128"},
       :id=>"I0-001-027148311-8"}},
   :withdrawn_note=>nil,
   :longitude=>"12.4833",
   :country_abbr=>"ITA",
   :region=>"Roma",
   :start_time=>"2016-04-26 10:00:00",
   :tz_id=>nil,
   :description=>
    " L’obiettivo del corso è quello di esplorare uno dei settori più innovativi degli ultimi anni: i tessuti interattivi. Dopo una breve introduzione ai principi base dell’elettronica e all’utilizzo delle schede di tipo Arduino per la prototipazione elettronica, saranno presentati esempi di prodotti tessili, tessuti, fili e fibre, dalle proprietà elettriche variabili o attive e la scheda Flora di Adafruit, compatibile Arduino, specificamente progettata per essere usata nell’ambito dell’industria tessile innovativa. I partecipanti potranno quindi esercitarsi nella realizzazione di prototipi comprendenti sensori tessili, LED e fibre conduttive. E’ indispensabile portare con sé il proprio PC portatile. ",
   :properties=>nil,
   :recurrence=>nil,
   :modified=>"2016-04-15 06:32:08",
   :venue_display=>"1",
   :tz_country=>nil,
   :performers=>nil,
   :price=>nil,
   :title=>"Workshop Wearable Technology - Roma",
   :parents=>nil,
   :geocode_type=>"City Based GeoCodes",
   :tz_olson_path=>nil,
   :city=>"Rome",
   :free=>nil,
   :trackbacks=>nil,
   :calendars=>nil,
   :country=>"Italy",
   :owner=>"evdb",
   :going=>nil,
   :country_abbr2=>"IT",
   :categories=>{:category=>[{:name=>"Science", :id=>"science"}]},
   :tags=>
    {:tag=>
      [{:owner=>"evdb", :id=>"eventbritecom", :title=>"eventbrite.com"},
       {:owner=>"evdb", :id=>"science", :title=>"science"},
       {:owner=>"evdb", :id=>"tickets", :title=>"tickets"}]},
   :venue_type=>"address",
   :created=>"2016-04-15 06:32:08",
   :venue_id=>"V0-001-009197611-7",
   :tz_city=>nil,
   :stop_time=>nil,
   :venue_name=>"Fablab Lazio, Roma Casilina"}
end
