
def evently_params
  {:withdrawn=>"0",
   :olson_path=>"Europe/Rome",
   :children=>nil,
   :comments=>nil,
   :region_abbr=>"RM",
   :postal_code=>nil,
   :latitude=>"41.9",
   :all_day=>"0",
   :groups=>nil,
   :url=>"http://rome.eventful.com/events/workshop-wearable-technology-roma-/E0-001-092704646-3?utm_source=apis&utm_medium=apim&utm_campaign=apic",
   :id=>"E0-001-092704646-3",
   :address=>"Via Casilina 3T",
   :privacy=>"1",
   :links=>
    {:link=>
      [{:time=>"2016-04-15 06:32:12",
        :url=>"http://www.eventbrite.it/e/biglietti-workshop-wearable-technology-roma-24664172203?aff=ebapi",
        :id=>"277760683",
        :type=>"Info",
        :description=>"Event details at eventbrite.com!",
        :username=>"evdb"}]},
   :images=>
    {:image=>
      {:small=>{:width=>"48", :url=>"http://s4.evcdn.com/images/small/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png", "height"=>"48"},
       :width=>"48",
       :creator=>nil,
       :thumb=>{:width=>"48", :url=>"http://s4.evcdn.com/images/thumb/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png", "height"=>"48"},
       :height=>"48",
       :url=>"http://s4.evcdn.com/images/small/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png",
       :medium=>{:width=>"128", :url=>"http://s4.evcdn.com/images/medium/I0-001/027/148/311-8.png_/workshop-wearable-technology-roma-11.png", "height"=>"128"},
       :id=>"I0-001-027148311-8"}},
   :withdrawn_note=>nil,
   :longitude=>"12.4833",
   :country_abbr=>"ITA",
   :region=>"Roma",
   :start_time=>"2016-04-26 10:00:00",
   :tz_id=>nil,
   :description=>
    " L’obiettivo del corso è quello di esplorare uno dei settori più innovativi degli ultimi anni: i tessuti interattivi. Dopo una breve introduzione ai principi base dell’elettronica e all’utilizzo delle schede di tipo Arduino per la prototipazione elettronica, saranno presentati esempi di prodotti tessili, tessuti, fili e fibre, dalle proprietà elettriche variabili o attive e la scheda Flora di Adafruit, compatibile Arduino, specificamente progettata per essere usata nell’ambito dell’industria tessile innovativa. I partecipanti potranno quindi esercitarsi nella realizzazione di prototipi comprendenti sensori tessili, LED e fibre conduttive. E’ indispensabile portare con sé il proprio PC portatile. ",
   :properties=>nil,
   :recurrence=>nil,
   :modified=>"2016-04-15 06:32:08",
   :venue_display=>"1",
   :tz_country=>nil,
   :performers=>nil,
   :price=>nil,
   :title=>"Workshop Wearable Technology - Roma",
   :parents=>nil,
   :geocode_type=>"City Based GeoCodes",
   :tz_olson_path=>nil,
   :city=>"Rome",
   :free=>nil,
   :trackbacks=>nil,
   :calendars=>nil,
   :country=>"Italy",
   :owner=>"evdb",
   :going=>nil,
   :country_abbr2=>"IT",
   :categories=>{:category=>[{:name=>"Science", :id=>"science"}]},
   :tags=>
    {:tag=>
      [{:owner=>"evdb", :id=>"eventbritecom", :title=>"eventbrite.com"},
       {:owner=>"evdb", :id=>"science", :title=>"science"},
       {:owner=>"evdb", :id=>"tickets", :title=>"tickets"}]},
   :venue_type=>"address",
   :created=>"2016-04-15 06:32:08",
   :venue_id=>"V0-001-009197611-7",
   :tz_city=>nil,
   :stop_time=>nil,
   :venue_name=>"Fablab Lazio, Roma Casilina"}
end

def loop_params_from_evently
  {:id=>"26",
   :title=>"Illustrator Corso base-intermedio targato Hexis",
   :description=>
    " Torna il corso Base-Intermedio di Illustrator targato Hexis il corso per scoprire i segreti del software vettoriale di casa Adobe Il corso base-intermedio di Adobe Illustrator verte sull’utilizzo di tutti gli strumenti vettoriali offerti dal software, incluse le nuove funzioni per la modifica del colore, i nuovi tools per disegnare, la nuova gestione dei tracciati e degli oggetti raggruppati e la nuova funzione per creare tavole da disegno multiple all’interno di un unico documento. Tutti questi strumenti, consentono all’utente di lavorare al top della qualità. A completare il corso, importanti nozioni, relative a colore, risoluzione, e differenze tra grafica raster e vettoriale. Qui si impara a fare le cose da grandi.   INTRODUZIONE Il corso Illustrator Base-Intermedio, è ideale per chi intende acquisire padronanza con l&#39;interfaccia e gli strumenti del più diffuso programma per creare immagini vettoriali. A CHI È RIVOLTO Chiunque desideri cominciare a utilizzare Illustrator, o migliorare le conoscenze base, il software per l&#39;elaborazione grafica vettoriale, standard professionale per illustratori, grafici e designer. OBIETTIVI • Conoscere l&#39;interfaccia del programma • Gestire le caratteristiche degli oggetti vettoriali • Avere da subito padronanza del software     PROGRAMMA GIORNATA: Ore 9:00 – inizio corso Ore 11:30/11:45 – coffe break Ore 13:00/14:00 – pausa pranzo Ore 15:30/15:45 – coffe break Ore 17:30 – Chiusura corso e consegna attestati     COSA POTRAI IMPARARE:  Nozioni di base  :: Area di lavoro  :: Tavole da disegno multiple  :: Panoramica degli strumenti  :: Righelli, griglie, guide e indicatori di ritaglio Creazione di un documento nuovo  :: I formati  :: I metodi di colore CMYK e RGB  :: Risoluzione effetti e modalità anteprima  :: I modelli di Illustrator La grafica vettoriale e gli strumenti  :: Concetto di grafica vettoriale :: Differenze con la grafica bitmap  :: Elementi fondamentali di disegno  :: Gli strumenti vettoriali e lo strumento penna  :: Le curve di Beziér  :: Il pannello elaborazione tracciati Selezione e disposizione oggetti :: Selezione degli oggetti  :: Raggruppamento ed espansione oggetti  :: Spostamento, allineamento e distribuzione degli oggetti  :: Utilizzo dei livelli  :: Pannello Trasforma  :: Ridimensiona e distorci oggetti  :: Taglio e divisione degli oggetti  :: Maschere di ritaglio Pannello Colori  :: Pannello campioni  :: Pannello Guida colori  :: Salvare i colori come campioni  :: Colorare con riempimenti e tracce  :: Applicazione dei colori e delle tinte  :: Le sfumature Lo strumento testo  :: Nuove funzionalità del pannello Testo  :: Immissione di un testo  :: Nozioni sui caratteri  :: Testo in area e testo grafico Effetti Speciali con filtri  :: Utilizzo generale dei filtri  :: Applicazione alle immagini vettoriali  :: Applicazione alle immagini bitmap  :: Creazione di un oggetto 3D Formati e interazioni  :: ll formato Illustrator  :: Interazione con Photoshop   Volete altre notizie o sapere se potete accedere ad altre forme di pagamento? Contattateci a corsi@hexisitalia.it o commerciale@hexisitalia.it Se preferite potete chiamarci ai numeri 02.89 65 02 71 02.90 60 51 72    FAQ Cosa posso portare e cosa non devo portare all&#39;evento? Dovrai portare un portatile con Illustrator installato, qualsiasi versione va bene ma se avessi la Creative Cloud sarebbe anche meglio   Dove posso contattare l&#39;organizzatore per qualsiasi domanda? Potete contattarci a queste mail - corsi@hexisitalia.it o commerciale@hexisitalia.it  oppure, se preferite potete chiamarci ai numeri - 02.89 65 02 71 - 02.90 60 51 72    Devo portare i biglietti stampati all&#39;evento? Assolutamente si, ci servirà per velocizzare le pratiche di accesso al corso   C&#39;è un numero minimo di partecipanti? Se Si, come si procede ad un corso che viene sospeso? Il numero minimo di partecipanti è 6, qual&#39;ora non si raggiunga il numero minimo di partecipanti gli iscritti vengono spostati al corso successivo.    Il nome sulla registrazione o sul biglietto non corrisponde a quello del partecipante. Ci sono problemi? Nessun problema, basta una breve comunicazione via mail che avvisi del nome e cognome effettivi del partecipante altrimenti avrà un attestato con il nome sbagliato   ",
   :start_time=>"2016-04-29T07:30:00.000Z",
   :event_url=>"http://rome.eventful.com/events/illustrator-corso-baseintermedio-targato-hexis-/E0-001-092536022-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
   :street_address=>nil,
   :city=>"Rome",
   :region_abbr=>"RM",
   :postal_code=>128,
   :country_abbr=>"ITA",
   :latitude=>"41.7858601",
   :longitude=>"12.4349129",
   :api_id=>"E0-001-092536022-6",
   :image_url=>"http://s2.evcdn.com/images/medium/I0-001/027/012/761-3.jpeg_/illustrator-corso-baseintermedio-targato-hexis-61.jpeg",
   :category_id=>1,
   :venue_id=>1,
   :creator=>nil,
   :user_events=>nil,
   :category=>{:id=>1, :name=>"Other &amp; Miscellaneous"},
   :venue=>{:id=>1, :name=>"Four Points by Sheraton Roma West Hotel"},
   :users=>nil,
   :comments=>nil,
   :format=>"json",
   :controller=>"api/v1/events",
   :action=>"update",
   :event=>
    {:id=>26,
     :title=>"Illustrator Corso base-intermedio targato Hexis",
     :description=>
      " Torna il corso Base-Intermedio di Illustrator targato Hexis il corso per scoprire i segreti del software vettoriale di casa Adobe Il corso base-intermedio di Adobe Illustrator verte sull’utilizzo di tutti gli strumenti vettoriali offerti dal software, incluse le nuove funzioni per la modifica del colore, i nuovi tools per disegnare, la nuova gestione dei tracciati e degli oggetti raggruppati e la nuova funzione per creare tavole da disegno multiple all’interno di un unico documento. Tutti questi strumenti, consentono all’utente di lavorare al top della qualità. A completare il corso, importanti nozioni, relative a colore, risoluzione, e differenze tra grafica raster e vettoriale. Qui si impara a fare le cose da grandi.   INTRODUZIONE Il corso Illustrator Base-Intermedio, è ideale per chi intende acquisire padronanza con l&#39;interfaccia e gli strumenti del più diffuso programma per creare immagini vettoriali. A CHI È RIVOLTO Chiunque desideri cominciare a utilizzare Illustrator, o migliorare le conoscenze base, il software per l&#39;elaborazione grafica vettoriale, standard professionale per illustratori, grafici e designer. OBIETTIVI • Conoscere l&#39;interfaccia del programma • Gestire le caratteristiche degli oggetti vettoriali • Avere da subito padronanza del software     PROGRAMMA GIORNATA: Ore 9:00 – inizio corso Ore 11:30/11:45 – coffe break Ore 13:00/14:00 – pausa pranzo Ore 15:30/15:45 – coffe break Ore 17:30 – Chiusura corso e consegna attestati     COSA POTRAI IMPARARE:  Nozioni di base  :: Area di lavoro  :: Tavole da disegno multiple  :: Panoramica degli strumenti  :: Righelli, griglie, guide e indicatori di ritaglio Creazione di un documento nuovo  :: I formati  :: I metodi di colore CMYK e RGB  :: Risoluzione effetti e modalità anteprima  :: I modelli di Illustrator La grafica vettoriale e gli strumenti  :: Concetto di grafica vettoriale :: Differenze con la grafica bitmap  :: Elementi fondamentali di disegno  :: Gli strumenti vettoriali e lo strumento penna  :: Le curve di Beziér  :: Il pannello elaborazione tracciati Selezione e disposizione oggetti :: Selezione degli oggetti  :: Raggruppamento ed espansione oggetti  :: Spostamento, allineamento e distribuzione degli oggetti  :: Utilizzo dei livelli  :: Pannello Trasforma  :: Ridimensiona e distorci oggetti  :: Taglio e divisione degli oggetti  :: Maschere di ritaglio Pannello Colori  :: Pannello campioni  :: Pannello Guida colori  :: Salvare i colori come campioni  :: Colorare con riempimenti e tracce  :: Applicazione dei colori e delle tinte  :: Le sfumature Lo strumento testo  :: Nuove funzionalità del pannello Testo  :: Immissione di un testo  :: Nozioni sui caratteri  :: Testo in area e testo grafico Effetti Speciali con filtri  :: Utilizzo generale dei filtri  :: Applicazione alle immagini vettoriali  :: Applicazione alle immagini bitmap  :: Creazione di un oggetto 3D Formati e interazioni  :: ll formato Illustrator  :: Interazione con Photoshop   Volete altre notizie o sapere se potete accedere ad altre forme di pagamento? Contattateci a corsi@hexisitalia.it o commerciale@hexisitalia.it Se preferite potete chiamarci ai numeri 02.89 65 02 71 02.90 60 51 72    FAQ Cosa posso portare e cosa non devo portare all&#39;evento? Dovrai portare un portatile con Illustrator installato, qualsiasi versione va bene ma se avessi la Creative Cloud sarebbe anche meglio   Dove posso contattare l&#39;organizzatore per qualsiasi domanda? Potete contattarci a queste mail - corsi@hexisitalia.it o commerciale@hexisitalia.it  oppure, se preferite potete chiamarci ai numeri - 02.89 65 02 71 - 02.90 60 51 72    Devo portare i biglietti stampati all&#39;evento? Assolutamente si, ci servirà per velocizzare le pratiche di accesso al corso   C&#39;è un numero minimo di partecipanti? Se Si, come si procede ad un corso che viene sospeso? Il numero minimo di partecipanti è 6, qual&#39;ora non si raggiunga il numero minimo di partecipanti gli iscritti vengono spostati al corso successivo.    Il nome sulla registrazione o sul biglietto non corrisponde a quello del partecipante. Ci sono problemi? Nessun problema, basta una breve comunicazione via mail che avvisi del nome e cognome effettivi del partecipante altrimenti avrà un attestato con il nome sbagliato   ",
     :start_time=>"2016-04-29T07:30:00.000Z",
     :event_url=>"http://rome.eventful.com/events/illustrator-corso-baseintermedio-targato-hexis-/E0-001-092536022-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
     :street_address=>nil,
     :city=>"Rome",
     :region_abbr=>"RM",
     :postal_code=>128,
     :country_abbr=>"ITA",
     :latitude=>"41.7858601",
     :longitude=>"12.4349129",
     :api_id=>"E0-001-092536022-6",
     :image_url=>"http://s2.evcdn.com/images/medium/I0-001/027/012/761-3.jpeg_/illustrator-corso-baseintermedio-targato-hexis-61.jpeg",
     :category_id=>1,
     :venue_id=>1,
     :creator=>nil}}
end

def new_loop_event_params
  {:title=>"The Best Party In Town",
   :description=>"We will do nothing all day.",
   :start_time=>"2040-10-10T00:00:00.000Z",
   :event_url=>"http://www.google.com",
   :street_address=>"725 5th Ave",
   :city=>"New York",
   :region_abbr=>"NY",
   :postal_code=>10022,
   :country_abbr=>"US",
   :image_url=>"https://upload.wikimedia.org/wikipedia/commons/d/d9/TrumpTower.JPG",
   :category=>"Other Miscellaneous",
   :venue=>"Trump Tower",
   :creator=>1}
end
